apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: mcutulo/argocd-fullcycle
  newTag: 645d96776107a16f0308874a8a516906d2b25a62
